name: Build Release

on:
  workflow_dispatch:
  push:
    tags:
      - 'v*'

permissions:
  contents: write

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Clone repository
        uses: actions/checkout@v4
      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: 3.24.2
      - run: flutter pub get
      - run: flutter build windows
      - name: copy files
        run: |
          cp C:\Windows\System32\msvcp140.dll build\windows\x64\runner\Release\
          cp C:\Windows\System32\vcruntime140.dll build\windows\x64\runner\Release\
          cp C:\Windows\System32\vcruntime140_1.dll build\windows\x64\runner\Release\

      - name: mv dist
        run: mv build\windows\x64\runner\Release\ image_tile_finder-${{ github.ref_name }}

      - name: Create Zip
        uses: thedoctor0/zip-release@09336613be18a8208dfa66bd57efafd9e2685657
        with:
          type: "zip"
          directory: .
          path: image_tile_finder-${{ github.ref_name }}
          filename: image_tile_finder-${{ github.ref_name }}.zip
          exclusions: "*.git*"

      - run: dart run msix:build
      - run: dart run msix:pack

      - name: Make Release
        uses: softprops/action-gh-release@1e07f4398721186383de40550babbdf2b84acfc5
        with:
          tag_name: ${{ github.ref_name }}
          files: |
            image_tile_finder-${{ github.ref_name }}.zip
            build\windows\x64\runner\Release\image_tile_finder.msix
